export type SupabaseProduct = {
  id: string;
  legacy_id: string | null;
  slug: string;
  source_id: string | null;
  source_url: string | null;
  name: string;
  arabic: string;
  tagline: string;
  short_description: string;
  description: string;
  price: number;
  old_price: number | null;
  category: string;
  family: string;
  concentration: string;
  size: string;
  notes_top: string[];
  notes_heart: string[];
  notes_base: string[];
  image_path: string | null;
  badge: string | null;
  rating: number;
  reviews_count: number;
  longevity: string;
  intensity: string;
  in_stock: boolean;
  featured: boolean;
  accent: string;
  published: boolean;
  created_at: string;
  updated_at: string;
};
